version: '2.3'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.6.2"
    container_name: es7
    environment:
      - node.name=es7
      - cluster.name=es-docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"